apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kraken.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      kraken.service: server
  template:
    metadata:
      labels:
        kraken.service: server
    spec:
      containers:
        - name: server
          env:
            - name: KRAKEN_CLICKHOUSE_ADDR
              value: clickhouse-proxy:9001
            - name: KRAKEN_CLICKHOUSE_PORT
              value: "9001"
            - name: KRAKEN_CLICKHOUSE_URL
              value: http://clickhouse:8123/
            - name: KRAKEN_DB_URL
              value: postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@postgres:5432/{{ .Values.postgresql.db }}
            - name: KRAKEN_MINIO_ADDR
              value: minio:9999
            - name: KRAKEN_PLANNER_URL
              value: http://controller:7997/
            - name: KRAKEN_REDIS_ADDR
              value: redis
            - name: KRAKEN_SERVER_ADDR
              value: server:6363
            - name: KRAKEN_SERVER_PORT
              value: "6363"
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.root_user }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.root_password }}
          image: "{{ .Values.image.baseUrl }}/kkserver:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 6363
      restartPolicy: Always
      serviceAccountName: kraken
status: {}
